language: node_js
node_js:
- '10'
before_install:
- rm -rf lib/
- npm install
- npm install -g typescript@4.0.3
- tsc
deploy:
  provider: npm
  email: work@denwilliams.net
  on:
    tags: true
    repo: denwilliams/node-flic-mqtt
  api_key:
    secure: AgF7Q0p2blzl6TB1hT04yMtzdvXkcipPnta6im+vUx9t8HN5um8gf79bb9tfiTH67PQuSv8TViU7WFeBYIhYUuqy5/pWyimWFb8MiS42cJfcR6lfXmvkqKbs4JNC/A227+Bj7GEvuCiWDzXYEjTpfHFwYR5S/MeSaOxOncaTwmCR+eEY9ytg7uRgknK9GMAq9BFJK+haz1RfJ6X6wc5iV/cAgyn9g/hAUm+XbF1pqTcqiK1rcUmoRRryRLw/tSWpu4MikyOKNhq40oOStu2XQM8j0ltTGRuP//1DJKPZofaTFKAek7ja04vDdRvWpZAiNnGrZBBApU2FVMYkeV1mO2OgqtA8H7VqRlEDgXBWL4GxAuATRlD6g5GjbFb4JMf+a/sxT1MaEnZHNnzEOwkrKhAQeX/k3VCm43IR5uMy1oqOT0L8fkSz4qkKur4OceW72xIHtMAbVjq9gpV1oISFKZCgKIB7VAeYk5wqOpItT+a4+L8MJBZTp+tLFqKLhwoIVueuyFZXfAqA96SlC/XAI51aJJoI3SGPJzr2Z0NASVj6k2dr9t6sVxlrD9ylcCwVOuBgYcTCnfbQrUEIrEL95+ZQJo/HJYFKPdHmJl8mnslg6F1DjtV4udoMF2cekhb9TOg/ihXX0EWKWQD8uHnK+ZxH7thRTC4QCVjme/piuqE=
