language: node_js
node_js:
  - "4"
before_install:
  - rm -rf lib/
  - npm install
  - npm install -g typescript@4.0.3
  - tsc
deploy:
  provider: npm
  email: work@denwilliams.net
  on:
    tags: true
    repo: denwilliams/node-flic-mqtt
  api_key:
    secure: asovUVhmmz099TsLR4bdcabHdKz8+xM6mVLLJrwaGkMPjWYpx+a1n+IOC+6TWYOzfQkKjoVuHPtip4zxRf3vP/wEb0KJcSAW3CzXnaP3NvCgTE3tll/GLglPCL2D3yQmVymX7cEhFhCPr73AJRFymhTT2VI+pf2adSGqBZkjakE8oNoT/56jMXFsmqYzfsKWafk0W9GUrkCiOoVdbGe8M3vtrr5cZo6aO8pbVOpvmgrLjD1be5ZXW981ZD94ijDYZVPpPKGlZ5syi3iutgL/zWTEqJOt/hbLJApI2evFAA9TvpDvwfiMj+lc7oKhO77UfmZ45G6r70dm6Fmurrkg6rnad2ZkHQ4PNEcZQQLNCPaTDCvoOq28FlCqVXRhWiIg8BId13AHjTVM93iEg5JJnd8omUrJRyLggiiKJE4QqdB8KiJQngMJ4KKKCqKm4BgAE9jLYOZocdGAgQIRhgafukjrbe0zbT2cwtg8ncE188w4YY9JxJ26AWlei/5tkHFronh6Q+uF/TIrMCN7D4/iGwIj8YZVFkuPGlZuuFmf5bZNVANqZE2GN7u4Ry5FlcuTwtpaiuPcmopGhURfcj9kb1a9VP4qrA6pD7GjY+d5lm1f7oMGJo+TowED8W5IrKqw+JVFb7nhRXAuyiR9E7LGPt9GORmYB2UfULvZ3jFZNnY=
